### ISSUE TITLE
Using NMEA messages with external mode

### ISSUE THREAD

**Issue by clydemcqueen** [waterlinked/blueos-ugps-extension#2]
We would like to configure the G2 to use external GPS and heading information from one or more NMEA 2000 sensors.

Ideally, the blueos-ugps-extension would listen for the appropriate NMEA messages and call the `/api/v1/external/master` API. In my proposed configuration, I would be sending NMEA 0183 GGA and HDG sentences in UDP packets from a YDEN-02 Ethernet Gateway.

BlueOS provides an [NMEA injection](https://github.com/bluerobotics/BlueOS-docker/tree/master/core/services/nmea_injector) service that might be a good reference.

Please [reference this thread on the BR forums](https://discuss.bluerobotics.com/t/positioning-error-present-with-waterlinked-ugps-system/14317/10).

Is this something you'd like to see in this extension? I'm happy to help develop this, test it, and so forth.

**Comment by clydemcqueen** [comment]
I wrote a few scripts to test NMEA injection. We tested this on a vessel with an NMEA 2000 network. https://github.com/clydemcqueen/wl_ugps_external

A few questions:
* how fast can I call /api/v/external/master? Is it reasonable to call it at 20Hz, or is that overkill?
* is the external heading and GPS filtered by the G2? Would it help to filter it before calling /api/v/external/master?

Thanks.

**Comment by clydemcqueen** [comment]
I created a simple BlueOS extension to run this script and provide a simple UI. https://github.com/bluerobotics/BlueOS-Extensions-Repository/pull/73

I'll close this out.

**Comment by wlseb** [comment]
Hi Clyde, just to follow up on this: It is best if you use the official water linked [support](https://waterlinked.com/support) for questions where you get a reply in 1-2 workdays.
